name: Run Playwright Tests Twice a Day

on:
  schedule:
    - cron: '0 0,12 * * *' # Runs at midnight and noon UTC every day
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the version you need for your project

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
        id: playwright-tests # Assign an ID for referencing results

      # Send Email Notification
      - name: Send Email Notification
        if: always() # Ensures email is sent regardless of success or failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: Playwright Test Run Completed - ${{ job.status }}
          body: |
            Hello,

            The Playwright test run has completed.
            - Status: ${{ job.status }}
            - Repository: ${{ github.repository }}
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}

            Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,
            GitHub Actions
          to: recipient@example.com
          from: ${{ secrets.GMAIL_USERNAME }}
