name: Run Playwright Tests and Send Notifications

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  # Run Playwright tests
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        id: playwright-tests

      - name: Archive Playwright HTML report
        if: always() # Ensure this runs even if tests fail
        run: zip -r playwright-report.zip playwright-report/
        continue-on-error: true
        id: archive-report

      - name: Upload Playwright report artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report.zip

      - name: Send Failure Notification
        if: failure() # Only runs if Playwright tests fail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: Playwright Test Run Failed - ${{ job.status }}
          body: |
            Hello,

            The Playwright test run has failed.
            - Repository: ${{ github.repository }}
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,
            GitHub Actions
          to: alexander.v.anderson@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}

  # Send daily report email
  daily_summary:
    runs-on: ubuntu-latest
    needs: run_tests # Ensure the test run completes before sending the email

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Daily Report Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: Daily Playwright Test Report
          body: |
            Hello,

            Here is the Playwright test report generated for the day.

            Regards,
            GitHub Actions
          to: alexander.v.anderson@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: playwright-report.zip # Attach the Playwright report
