name: Run Playwright Tests and Send Daily Summary

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
    - cron: '0 0 * * *' # Runs at midnight UTC for the daily summary
  workflow_dispatch: # Allows manual trigger

jobs:
  # Hourly test runs
  hourly_tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule != '0 0 * * *'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        id: playwright-tests

      - name: Send Failure Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: Playwright Test Run Failed
          body: |
            Hello,

            The Playwright test run has failed.
            - Repository: ${{ github.repository }}
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,
            GitHub Actions
          to: alexander.v.anderson@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}

  # Daily summary email
  daily_summary:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Zip Playwright Report
        run: |
          zip -r playwright-report.zip playwright-report/
        id: zip-report

      - name: Send Daily Summary Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: Daily Playwright Test Summary
          body: |
            Hello,

            Attached is the Playwright HTML report summary for today.

            Regards,
            GitHub Actions
          to: alexander.v.kolesnyk@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: playwright-report.zip
