name: Run Playwright Tests Twice a Day

on:
  schedule:
    - cron: '0 0,12 * * *'  # This cron expression runs the workflow at midnight and noon UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: |
          npm ci  # If you're using npm and have a package-lock.json
          # or if you're using yarn, replace it with: yarn install

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps  # Install browsers needed for Playwright

      - name: Run Playwright tests
        run: |
          npx playwright test  # Run the Playwright tests
